# Project information
site_name: tfod-steps
site_author: Sunny Bhaveen Chandra
site_description: >-
  steps to setup tfod
# Repository
repo_name: c17hawke/tfod-steps
repo_url: https://github.com/c17hawke/tfod-steps/

# Configuration
theme:
  name: material
  features:
    - tabs
  language: en
  palette:
    primary: green
    accent: green

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight

copyright: |
  &copy; 2020 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>